
import React from 'react';
import { ToolCategory, ToolDefinition, ToolID } from './types';

// Icons using SVG for no dependencies
const Icons = {
  PDF: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 2H7a2 2 0 00-2 2v15a2 2 0 002 2z" /></svg>,
  Image: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>,
  Edit: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" /></svg>,
  Check: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>,
  Globe: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>,
  Shield: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>,
  List: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 10h16M4 14h16M4 18h16" /></svg>,
  FileText: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>,
  Crop: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 4V1m0 3h10a1 1 0 011 1v10h3m-3 0h-3m-3 0H4a1 1 0 01-1-1V4h3m3 0v10" /></svg>,
  Palette: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01" /></svg>,
  Refresh: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>,
  Split: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m-8-8h16" /></svg>,
  Combine: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7v8a2 2 0 002 2h6M8 7V5a2 2 0 012-2h4.586a1 1 0 01.707.293l4.414 4.414a1 1 0 01.293.707V15a2 2 0 01-2 2h-2M8 7H6a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 00-2-2v-2" /></svg>,
  BarChart: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>,
  Code: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" /></svg>,
  Calculator: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" /></svg>,
  Key: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 011.293-.914L10 14m-4 0a3 3 0 11-6 0 3 3 0 016 0zm-3 2a2 2 0 100-4 2 2 0 000 4z" /></svg>,
  Unlock: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 11V7a4 4 0 118 0m-4 8v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2z" /></svg>,
  Lock: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>,
  Compress: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 9V3M10 9l3 3m-3-3l-3 3m-3 4h14m-10 4h6m4-4V3" /></svg>,
  Numbers: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 14l2-2m0 0l2 2m-2-2V4m0 16a2 2 0 01-2-2V6a2 2 0 012-2h4a2 2 0 012 2v12a2 2 0 01-2 2h-4z" /></svg>,
  Text: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 4v16m6-16v16M3 8h18M3 16h18" /></svg>,
  Html: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" /></svg>,
  Epub: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.246 18 16.5 18c-1.747 0-3.332.477-4.5 1.253" /></svg>,
  Rotate: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg>,
  Word: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>,
  Excel: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17v-6a2 2 0 012-2h2a2 2 0 012 2v6m-4 0V9m-4 8h8a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>,
  PowerPoint: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" /></svg>,
  JPG: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>,
  PNG: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>,
  CSV: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17v-6a2 2 0 012-2h2a2 2 0 012 2v6m-4 0V9m-4 8h8a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>,
  XML: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" /></svg>,
  JSON: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 11c0 1.656-1.344 3-3 3s-3-1.344-3-3 1.344-3 3-3 3 1.344 3 3zm0 0c0-1.656 1.344-3 3-3s3 1.344 3 3-1.344 3-3 3-3-1.344-3-3zM3 12h18" /></svg>,
  Link: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.102 1.101" /></svg>,
  Share: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12s-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.368a3 3 0 105.367 2.684 3 3 0 00-5.367-2.684z" /></svg>,
  Video: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>,
  Ruler: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>, 
  Scale: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" /></svg>,
  Thermometer: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>,
  Beaker: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.384-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" /></svg>,
  Gauge: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>, 
  Database: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" /></svg>,
  Clock: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>,
  Fuel: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>,
  Pen: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" /></svg>,
  Wave: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 12c2.5-4 4.5-4 7 0s4.5 4 7 0" /></svg>,
  Angle: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 19h16M4 19L14 4" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 19c0-2.5 1.5-4.5 4-4.5" /></svg>,
  Triangle: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4L3 20h18L12 4z" /></svg>,
  Circle: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><circle cx="12" cy="12" r="10" strokeWidth={2} /></svg>,
  Cube: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" /></svg>,
  Shoe: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" /></svg>,
  Dragon: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>,
  Binary: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" /></svg>,
  Walk: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>,
  Trash: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>,
  Move: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" /></svg>,
  Water: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 14.66V20a2 2 0 01-2 2H4a2 2 0 01-2-2V6a2 2 0 012-2h2.34M20 14.66a9 9 0 01-1.34-4.66 9 9 0 01-9-9M20 14.66a9 9 0 00-9 9" /></svg>,
  Wrench: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /></svg>,
  Search: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>,
  Quote: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" /></svg>,
  Date: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>,
  Stopwatch: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0zM15 19l-7-7 7-7" /></svg>,
  Timer: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" /></svg>,
  Work: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>,
  Bolt: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>,
  LightBulb: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" /></svg>,
  Eye: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" /></svg>,
};

export const TOOLS: ToolDefinition[] = [
  // --- PDF & File Tools ---
  { id: ToolID.PDF_EDITOR, title: 'PDF Editor', description: 'Edit PDF files online. Add text, shapes, images, and freehand drawings.', icon: Icons.Edit, category: ToolCategory.PDF, isPopular: true, implemented: true },
  { id: ToolID.ESIGN_PDF, title: 'eSign PDF', description: 'Sign PDF documents electronically with your digital signature.', icon: Icons.Pen, category: ToolCategory.PDF, isPopular: true, implemented: true }, 
  { id: ToolID.PDF_MERGE, title: 'Merge PDF', description: 'Combine multiple PDF files into one.', icon: Icons.Combine, category: ToolCategory.PDF, isPopular: true, implemented: true },
  { id: ToolID.SPLIT_PDF, title: 'Split PDF', description: 'Extract specific pages from your PDF.', icon: Icons.Split, category: ToolCategory.PDF, isPopular: true, implemented: true },
  { id: ToolID.DELETE_PDF_PAGES, title: 'Delete PDF Pages', description: 'Remove unwanted pages from a PDF document.', icon: Icons.Trash, category: ToolCategory.PDF, implemented: true }, 
  { id: ToolID.REARRANGE_PDF, title: 'Rearrange PDF', description: 'Reorder pages within a PDF file.', icon: Icons.Move, category: ToolCategory.PDF, implemented: true }, 
  { id: ToolID.REPAIR_PDF, title: 'Repair PDF', description: 'Recover data from a corrupted or damaged PDF document.', icon: Icons.Wrench, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.COMPRESS_PDF, title: 'Compress PDF', description: 'Reduce PDF file size without losing quality.', icon: Icons.Compress, isPopular: true, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.WORD_TO_PDF, title: 'Word to PDF', description: 'Convert DOCX/DOC to PDF.', icon: Icons.Word, category: ToolCategory.PDF, isPopular: true, implemented: true },
  { id: ToolID.PDF_TO_WORD, title: 'PDF to Word', description: 'Convert PDF to editable Word (DOCX).', icon: Icons.Word, isPopular: true, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.JPG_TO_PDF, title: 'JPG to PDF', description: 'Convert JPG images to PDF.', icon: Icons.JPG, category: ToolCategory.PDF, isPopular: true, implemented: true },
  { id: ToolID.PNG_TO_PDF, title: 'PNG to PDF', description: 'Convert PNG images to PDF.', icon: Icons.PNG, isPopular: true, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.GIF_TO_PDF, title: 'GIF to PDF', description: 'Convert GIF images to PDF.', icon: Icons.Image, category: ToolCategory.PDF, implemented: true }, 
  { id: ToolID.IMAGE_TO_PDF, title: 'Image to PDF', description: 'Convert various images to PDF.', icon: Icons.Image, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.PDF_TO_JPG, title: 'PDF to JPG', description: 'Convert PDF pages to JPG.', icon: Icons.JPG, isPopular: true, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.PDF_TO_PNG, title: 'PDF to PNG', description: 'Convert PDF pages to PNG.', icon: Icons.PNG, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.UNLOCK_PDF, title: 'Unlock PDF', description: 'Remove PDF passwords.', icon: Icons.Unlock, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.LOCK_PDF, title: 'Protect PDF', description: 'Add password to PDF.', icon: Icons.Lock, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.ROTATE_PDF, title: 'Rotate PDF', description: 'Rotate PDF pages.', icon: Icons.Refresh, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.ADD_WATERMARK, title: 'Add Watermark', description: 'Add text watermark to your PDF.', icon: Icons.Water, category: ToolCategory.PDF, implemented: true }, 
  { id: ToolID.ADD_PAGE_NUMBERS, title: 'Add Page Numbers', description: 'Insert page numbers into PDF.', icon: Icons.Numbers, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.PDF_TO_EXCEL, title: 'PDF to Excel', description: 'Convert PDF tables to Excel.', icon: Icons.Excel, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.EXCEL_TO_PDF, title: 'Excel to PDF', description: 'Convert Excel to PDF.', icon: Icons.Excel, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.PDF_TO_POWERPOINT, title: 'PDF to PowerPoint', description: 'Convert PDF to PPTX.', icon: Icons.PowerPoint, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.POWERPOINT_TO_PDF, title: 'PowerPoint to PDF', description: 'Convert PPTX to PDF.', icon: Icons.PowerPoint, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.PDF_TO_TEXT, title: 'PDF to Text', description: 'Extract text from PDF.', icon: Icons.FileText, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.PDF_TO_HTML, title: 'PDF to HTML', description: 'Convert PDF to HTML.', icon: Icons.Html, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.PDF_TO_EPUB, title: 'PDF to ePub', description: 'Convert PDF to ePub.', icon: Icons.Epub, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.EPUB_TO_PDF, title: 'ePub to PDF', description: 'Convert ePub to PDF.', icon: Icons.Epub, category: ToolCategory.PDF, implemented: true },
  { id: ToolID.CROP_PDF, title: 'Crop PDF', description: 'Trim PDF pages.', icon: Icons.Crop, category: ToolCategory.PDF, implemented: true },
  
  // --- Image Tools (Basic) ---
  { id: ToolID.COMPRESS_IMAGE, title: 'Compress Image', description: 'Reduce image size.', icon: Icons.Compress, isPopular: true, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.RESIZE_IMAGE, title: 'Resize Image', description: 'Change image dimensions.', icon: Icons.Crop, isPopular: true, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.CROP_IMAGE, title: 'Crop Image', description: 'Crop image custom area.', icon: Icons.Crop, isPopular: true, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.ROTATE_IMAGE, title: 'Rotate Image', description: 'Rotate image 90 degrees.', icon: Icons.Refresh, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.ROUND_IMAGE, title: 'Round Image', description: 'Circle crop image.', icon: Icons.Palette, isPopular: true, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.FLIP_IMAGE, title: 'Flip Image', description: 'Flip horizontally/vertically.', icon: Icons.Refresh, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.TO_GRAYSCALE, title: 'Grayscale Image', description: 'Convert to grayscale.', icon: Icons.Palette, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.BLACK_AND_WHITE, title: 'Black & White Image', description: 'Convert to B&W.', icon: Icons.Palette, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.IMAGE_TO_SKETCH, title: 'Image to Sketch', description: 'Convert photo to pencil sketch.', icon: Icons.Edit, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.IMAGE_TO_BASE64, title: 'Image to Base64', description: 'Convert image file to Base64 string.', icon: Icons.Code, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.BASE64_TO_IMAGE, title: 'Base64 to Image', description: 'Convert Base64 string to image file.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  
  // --- Image Tools (Converters) ---
  { id: ToolID.HEIC_TO_JPG, title: 'HEIC to JPG', description: 'Convert HEIC to JPG.', icon: Icons.JPG, category: ToolCategory.IMAGE, isPopular: true, implemented: true },
  { id: ToolID.PNG_TO_JPG, title: 'PNG to JPG', description: 'Convert PNG to JPG.', icon: Icons.JPG, category: ToolCategory.IMAGE, isPopular: true, implemented: true },
  { id: ToolID.WEBP_TO_JPG, title: 'WebP to JPG', description: 'Convert WebP to JPG.', icon: Icons.JPG, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.JPG_TO_PNG, title: 'JPG to PNG', description: 'Convert JPG to PNG.', icon: Icons.PNG, category: ToolCategory.IMAGE, isPopular: true, implemented: true },
  { id: ToolID.PNG_TO_WEBP, title: 'PNG to WebP', description: 'Convert PNG to WebP.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.JPG_TO_WEBP, title: 'JPG to WebP', description: 'Convert JPG to WebP.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.HEIC_TO_PNG, title: 'HEIC to PNG', description: 'Convert HEIC to PNG.', icon: Icons.PNG, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.SVG_TO_PNG, title: 'SVG to PNG', description: 'Convert SVG to PNG.', icon: Icons.PNG, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.GIF_TO_MP4, title: 'GIF to MP4', description: 'Convert GIF animations to MP4 video.', icon: Icons.Video, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.JPG_TO_GIF, title: 'JPG to GIF', description: 'Convert JPG images to GIF.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.TIFF_TO_JPG, title: 'TIFF to JPG', description: 'Convert TIFF to JPG.', icon: Icons.JPG, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.WEBP_TO_GIF, title: 'WebP to GIF', description: 'Convert WebP to GIF.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.PNG_TO_EPS, title: 'PNG to EPS', description: 'Convert PNG to EPS vector.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.PNG_TO_GIF, title: 'PNG to GIF', description: 'Convert PNG to GIF.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.JPG_TO_TIFF, title: 'JPG to TIFF', description: 'Convert JPG to TIFF.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.EPS_TO_PNG, title: 'EPS to PNG', description: 'Convert EPS to PNG.', icon: Icons.PNG, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.TIFF_TO_PNG, title: 'TIFF to PNG', description: 'Convert TIFF to PNG.', icon: Icons.PNG, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.GIF_TO_PNG, title: 'GIF to PNG', description: 'Convert GIF to PNG.', icon: Icons.PNG, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.PNG_TO_TIFF, title: 'PNG to TIFF', description: 'Convert PNG to TIFF.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.EPS_TO_JPG, title: 'EPS to JPG', description: 'Convert EPS to JPG.', icon: Icons.JPG, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.EPS_TO_SVG, title: 'EPS to SVG', description: 'Convert EPS to SVG.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.JPG_TO_AVIF, title: 'JPG to AVIF', description: 'Convert JPG to AVIF.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.GIF_TO_AVIF, title: 'GIF to AVIF', description: 'Convert GIF to AVIF.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.PNG_TO_AVIF, title: 'PNG to AVIF', description: 'Convert PNG to AVIF.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.PSD_TO_SVG, title: 'PSD to SVG', description: 'Convert PSD to SVG.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.TIFF_TO_SVG, title: 'TIFF to SVG', description: 'Convert TIFF to SVG.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.WEBP_TO_AVIF, title: 'WebP to AVIF', description: 'Convert WebP to AVIF.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.HEIC_TO_AVIF, title: 'HEIC to AVIF', description: 'Convert HEIC to AVIF.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.PNG_TO_HEIC, title: 'PNG to HEIC', description: 'Convert PNG to HEIC.', icon: Icons.Image, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.VSD_TO_JPG, title: 'VSD to JPG', description: 'Convert Visio to JPG.', icon: Icons.JPG, category: ToolCategory.IMAGE, implemented: true },
  { id: ToolID.VSDX_TO_JPG, title: 'VSDX to JPG', description: 'Convert Visio to JPG.', icon: Icons.JPG, category: ToolCategory.IMAGE, implemented: true },
  
  // --- SEO Tools ---
  { id: ToolID.META_TAG_GENERATOR, title: 'Meta Tag Generator', description: 'Create SEO-friendly meta tags.', icon: Icons.Code, category: ToolCategory.SEO, isPopular: true, implemented: true },
  { id: ToolID.KEYWORD_DENSITY_CHECKER, title: 'Keyword Density', description: 'Check keyword usage frequency.', icon: Icons.BarChart, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.HEADING_TAG_ANALYZER, title: 'Heading Analyzer', description: 'Analyze H1-H6 tags.', icon: Icons.List, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.ALT_TEXT_GENERATOR, title: 'Alt Text Gen', description: 'Generate image alt tags.', icon: Icons.Image, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.ROBOTS_TXT_GENERATOR, title: 'Robots.txt Gen', description: 'Create robots.txt file.', icon: Icons.Code, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.SITEMAP_GENERATOR, title: 'Sitemap Gen', description: 'Generate XML sitemap.', icon: Icons.List, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.OPEN_GRAPH_GENERATOR, title: 'Open Graph Gen', description: 'Create social media tags.', icon: Icons.Share, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.SCHEMA_MARKUP_GENERATOR, title: 'Schema Gen', description: 'Generate JSON-LD schema.', icon: Icons.Code, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.CANONICAL_TAG_GENERATOR, title: 'Canonical Tag Gen', description: 'Create canonical links.', icon: Icons.Link, category: ToolCategory.SEO, implemented: true },
  // New SEO Tools
  { id: ToolID.GOOGLE_SERP_SIMULATOR, title: 'Google SERP Sim', description: 'Preview your page in search results.', icon: Icons.Search, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.UTM_LINK_GENERATOR, title: 'UTM Link Gen', description: 'Build tracking URLs for campaigns.', icon: Icons.Link, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.KEYWORD_PERMUTATION_GENERATOR, title: 'Keyword Permutation', description: 'Combine keyword lists.', icon: Icons.Refresh, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.HTACCESS_REDIRECT_GENERATOR, title: '.htaccess Redirect', description: 'Generate 301 redirects.', icon: Icons.Code, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.HTML_TEXT_RATIO_CALCULATOR, title: 'HTML Text Ratio', description: 'Calculate text to code ratio.', icon: Icons.Calculator, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.PPC_KEYWORD_WRAPPER, title: 'PPC Keyword Wrapper', description: 'Wrap keywords for ads.', icon: Icons.Quote, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.BULK_URL_OPENER, title: 'Bulk URL Opener', description: 'Open multiple URLs at once.', icon: Icons.Link, category: ToolCategory.SEO, implemented: true },
  { id: ToolID.LINK_EXTRACTOR, title: 'Link Extractor', description: 'Extract links from HTML.', icon: Icons.Link, category: ToolCategory.SEO, implemented: true },

  // --- Text & Encoding Tools ---
  { id: ToolID.URL_SANITIZER, title: 'URL Sanitizer/Cleaner', description: 'Remove tracking parameters (UTM, fbclid, etc.) from URLs.', icon: Icons.Link, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.CHARACTER_COUNTER, title: 'Character Counter', description: 'Count characters and words.', icon: Icons.Numbers, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.WORD_COUNTER, title: 'Word Counter', description: 'Count words and sentences.', icon: Icons.Numbers, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.READABILITY_SCORE, title: 'Readability Score', description: 'Analyze text readability.', icon: Icons.FileText, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.LOREM_IPSUM_GENERATOR, title: 'Lorem Ipsum Gen', description: 'Generate placeholder text in various formats and styles.', icon: Icons.Text, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.TEXT_TO_BINARY, title: 'Text to Binary', description: 'Convert text to binary code.', icon: Icons.Binary, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.BINARY_TO_TEXT, title: 'Binary to Text', description: 'Convert binary code to text.', icon: Icons.Binary, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.MORSE_CODE_TRANSLATOR, title: 'Morse Code Translator', description: 'Translate text to Morse code and vice versa.', icon: Icons.Code, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.MORSE_CODE_GENERATOR, title: 'Morse Code Generator', description: 'Generate Morse code from text.', icon: Icons.Code, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.LEET_SPEAK_TRANSLATOR, title: 'Leet Speak Translator', description: 'Convert text to 1337 sp34k.', icon: Icons.Code, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.BASE64_ENCODER_DECODER, title: 'Base64 Encode/Decode', description: 'Convert text to Base64 and back.', icon: Icons.Code, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.URL_ENCODER_DECODER, title: 'URL Encode/Decode', description: 'Encode or decode URL strings.', icon: Icons.Link, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.CASE_CONVERTER, title: 'Case Converter', description: 'UPPERCASE, lowercase, Title Case, etc.', icon: Icons.Text, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.JSON_FORMATTER, title: 'JSON Formatter', description: 'Prettify or minify JSON data.', icon: Icons.Code, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.REMOVE_DUPLICATE_LINES, title: 'Remove Duplicates', description: 'Remove duplicate lines from text.', icon: Icons.List, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.TEXT_REVERSER, title: 'Text Reverser', description: 'Reverse text or words.', icon: Icons.Refresh, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.SLUG_GENERATOR, title: 'Slug Generator', description: 'Create SEO-friendly URL slugs.', icon: Icons.Link, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.HASH_GENERATOR, title: 'MD5 Hash Generator', description: 'Generate MD5 hashes.', icon: Icons.Shield, category: ToolCategory.TEXT, implemented: true },
  
  // New Text Tools
  { id: ToolID.TEXT_DIFF_CHECKER, title: 'Text Diff Checker', description: 'Compare two texts side-by-side.', icon: Icons.Split, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.UUID_GENERATOR, title: 'UUID Generator', description: 'Generate random UUIDs/GUIDs.', icon: Icons.Key, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.HTML_ENTITY_ENCODER, title: 'HTML Entity Encoder', description: 'Encode/Decode HTML special chars.', icon: Icons.Code, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.LIST_SORTER, title: 'List Sorter', description: 'Sort lists alphabetically or numerically.', icon: Icons.List, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.PASSWORD_GENERATOR, title: 'Password Generator', description: 'Create strong, secure passwords.', icon: Icons.Lock, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.STRIP_HTML, title: 'Strip HTML Tags', description: 'Remove HTML tags from text.', icon: Icons.Code, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.ADD_LINE_NUMBERS, title: 'Add Line Numbers', description: 'Number each line of text.', icon: Icons.List, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.COLOR_CONVERTER, title: 'Color Converter', description: 'Convert HEX, RGB, HSL.', icon: Icons.Palette, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.URL_DECODER, title: 'URL Decoder', description: 'Decode URL-encoded text back to standard format.', icon: Icons.Link, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.URL_ENCODER, title: 'URL Encoder', description: 'Encode text for safe use in URLs.', icon: Icons.Link, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.SHA1_GENERATOR, title: 'SHA-1 Generator', description: 'Generate SHA-1 hash from text.', icon: Icons.Shield, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.SHA256_GENERATOR, title: 'SHA-256 Generator', description: 'Generate SHA-256 hash from text.', icon: Icons.Shield, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.SHA384_GENERATOR, title: 'SHA-384 Generator', description: 'Generate SHA-384 hash from text.', icon: Icons.Shield, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.SHA512_GENERATOR, title: 'SHA-512 Generator', description: 'Generate SHA-512 hash from text.', icon: Icons.Shield, category: ToolCategory.TEXT, implemented: true },
  { id: ToolID.TEXT_STATISTICS, title: 'Text Statistics', description: 'Detailed analysis of text content.', icon: Icons.BarChart, category: ToolCategory.TEXT, implemented: true },

  // --- Unit Converter Tools ---
  { id: ToolID.LENGTH_CONVERTER, title: 'Length Converter', description: 'Convert between various length units including meters, kilometers, feet, inches, miles, and yards. Ideal for construction, education, and daily measurements.', icon: Icons.Calculator, category: ToolCategory.UNIT_CONVERTER, isPopular: true, implemented: true },
  { id: ToolID.WEIGHT_CONVERTER, title: 'Weight Converter', description: 'Easily convert weight units such as kilograms, grams, pounds, ounces, and stones. Useful for cooking, shipping, and science.', icon: Icons.Scale, category: ToolCategory.UNIT_CONVERTER, isPopular: true, implemented: true },
  { id: ToolID.TEMPERATURE_CONVERTER, title: 'Temperature Converter', description: 'Convert temperatures between Celsius, Fahrenheit, and Kelvin scales. Essential for science, weather, and cooking applications.', icon: Icons.Thermometer, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.AREA_CONVERTER, title: 'Area Converter', description: 'Calculate area conversions for square meters, square feet, acres, hectares, and more. Perfect for real estate and land measurement.', icon: Icons.Crop, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.VOLUME_CONVERTER, title: 'Volume Converter', description: 'Convert volume measurements like liters, milliliters, gallons, quarts, pints, and cups. Great for recipes and liquid measurements.', icon: Icons.Beaker, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.SPEED_CONVERTER, title: 'Speed Converter', description: 'Convert speed units including miles per hour (mph), kilometers per hour (km/h), knots, and meters per second.', icon: Icons.Gauge, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.DATA_CONVERTER, title: 'Data Size Converter', description: 'Convert digital storage units from Bytes to Kilobytes, Megabytes, Gigabytes, Terabytes, and Petabytes.', icon: Icons.Database, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.TIME_CONVERTER, title: 'Time Unit Converter', description: 'Convert time durations between seconds, minutes, hours, days, weeks, months, and years.', icon: Icons.Clock, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.FUEL_CONVERTER, title: 'Fuel Efficiency', description: 'Convert fuel efficiency between Miles per Gallon (US/UK) and Liters per 100 Kilometers. Useful for comparing vehicle efficiency.', icon: Icons.Fuel, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.PRESSURE_CONVERTER, title: 'Pressure Converter', description: 'Convert pressure readings between Pascal, Bar, PSI, Atmosphere, and Torr. Essential for engineering and tire pressure.', icon: Icons.Gauge, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.FREQUENCY_CONVERTER, title: 'Frequency Converter', description: 'Convert frequency units including Hertz, Kilohertz, Megahertz, Gigahertz, and RPM.', icon: Icons.Wave, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.ANGLE_CONVERTER, title: 'Angle Converter', description: 'Convert geometric angles between Degrees, Radians, Gradians, Arcminutes, and Arcseconds.', icon: Icons.Angle, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  
  // New Unit Converters
  { id: ToolID.POWER_CONVERTER, title: 'Power Converter', description: 'Convert power units such as Watts, Kilowatts, Horsepower, and Joules per second. Useful for electrical and mechanical calculations.', icon: Icons.Bolt, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.ENERGY_CONVERTER, title: 'Energy Converter', description: 'Convert energy units including Joules, Calories, Kilowatt-hours, and BTUs. Helpful for physics, nutrition, and energy consumption.', icon: Icons.Bolt, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.NUMBER_BASE_CONVERTER, title: 'Number Base Converter', description: 'Convert numbers between Binary (Base 2), Octal (Base 8), Decimal (Base 10), and Hexadecimal (Base 16) formats.', icon: Icons.Binary, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.BITRATE_CONVERTER, title: 'Bitrate Converter', description: 'Convert data transfer rates between bits per second, Kilobits, Megabits (Mbps), Gigabits, and Byte-based rates like MB/s.', icon: Icons.Gauge, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.TORQUE_CONVERTER, title: 'Torque Converter', description: 'Convert torque values between Newton-meters, Pound-feet, Pound-inches, and Kilogram-meters. Essential for mechanics.', icon: Icons.Refresh, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.FORCE_CONVERTER, title: 'Force Converter', description: 'Convert force units such as Newtons, Kilonewtons, Pound-force, Kilogram-force, and Dynes.', icon: Icons.Scale, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.DENSITY_CONVERTER, title: 'Density Converter', description: 'Convert density measurements between kilograms per cubic meter, grams per cubic centimeter, and imperial density units.', icon: Icons.Beaker, category: ToolCategory.UNIT_CONVERTER, implemented: true },
  { id: ToolID.ILLUMINANCE_CONVERTER, title: 'Illuminance Converter', description: 'Convert illuminance units between Lux, Foot-candles, and Phot. Useful for lighting design and photography.', icon: Icons.LightBulb, category: ToolCategory.UNIT_CONVERTER, implemented: true },

  { id: ToolID.SHOES_SIZE_CONVERTER, title: 'Shoe Size Converter', description: 'Convert between US, UK, EU sizes.', icon: Icons.Shoe, category: ToolCategory.OTHER, implemented: true },

  // --- Math & Science Tools ---
  { id: ToolID.TRIANGLE_CALCULATOR, title: 'Triangle Calculator', description: 'Calculate area, perimeter, and sides.', icon: Icons.Triangle, category: ToolCategory.MATH_SCIENCE, isPopular: true, implemented: true },
  { id: ToolID.VOLUME_CALCULATOR, title: 'Volume Calculator', description: 'Calculate volume of various shapes.', icon: Icons.Cube, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.SLOPE_CALCULATOR, title: 'Slope Calculator', description: 'Find slope, distance, and angle.', icon: Icons.Refresh, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.AREA_CALCULATOR, title: 'Area Calculator', description: 'Calculate area of geometric shapes.', icon: Icons.Crop, category: ToolCategory.MATH_SCIENCE, isPopular: true, implemented: true },
  { id: ToolID.DISTANCE_CALCULATOR, title: 'Distance Calculator', description: 'Calculate distance between two points.', icon: Icons.Ruler, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.CIRCLE_CALCULATOR, title: 'Circle Calculator', description: 'Calculate area, circumference, radius.', icon: Icons.Circle, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.SURFACE_AREA_CALCULATOR, title: 'Surface Area Calc', description: 'Calculate surface area of 3D objects.', icon: Icons.Cube, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.PYTHAGOREAN_CALCULATOR, title: 'Pythagorean Calc', description: 'Calculate hypotenuse of right triangle.', icon: Icons.Triangle, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.RIGHT_TRIANGLE_CALCULATOR, title: 'Right Triangle Calc', description: 'Solve for sides and angles.', icon: Icons.Triangle, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.LCM_GCD_CALCULATOR, title: 'LCM & GCD Calc', description: 'Find Least Common Multiple & Greatest Common Divisor.', icon: Icons.Calculator, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.PERCENTAGE_TO_CGPA, title: 'Percentage to CGPA', description: 'Convert academic percentage to CGPA.', icon: Icons.Calculator, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.BINARY_CALCULATOR, title: 'Binary Calculator', description: 'Perform math with binary numbers.', icon: Icons.Binary, category: ToolCategory.OTHER, implemented: true },
  
  // New Math & Science Tools
  { id: ToolID.PERCENTAGE_CALCULATOR, title: 'Percentage Calculator', description: 'Calculate percentages, increases, and decreases.', icon: Icons.Calculator, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.STATISTICS_CALCULATOR, title: 'Statistics Calculator', description: 'Calculate mean, median, mode, and standard deviation.', icon: Icons.BarChart, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.QUADRATIC_SOLVER, title: 'Quadratic Solver', description: 'Solve quadratic equations and find roots.', icon: Icons.Wave, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.FRACTION_CALCULATOR, title: 'Fraction Calculator', description: 'Add, subtract, multiply, and divide fractions.', icon: Icons.Calculator, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.PERMUTATION_COMBINATION_CALCULATOR, title: 'Permutation & Combination', description: 'Calculate nPr and nCr values.', icon: Icons.Numbers, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.PRIME_FACTORIZATION_TOOL, title: 'Prime Factorization', description: 'Find prime factors of a number.', icon: Icons.Numbers, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.FORCE_CALCULATOR, title: 'Force Calculator', description: 'Calculate Force, Mass, or Acceleration (F=ma).', icon: Icons.Bolt, category: ToolCategory.MATH_SCIENCE, implemented: true },
  { id: ToolID.OHMS_LAW_CALCULATOR, title: 'Ohm\'s Law Calc', description: 'Calculate Voltage, Current, Resistance, Power.', icon: Icons.Bolt, category: ToolCategory.MATH_SCIENCE, implemented: true },

  // --- Financial Tools ---
  { id: ToolID.LOAN_CALCULATOR, title: 'Loan Calculator', description: 'Calculate loan payments.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, isPopular: true, implemented: true },
  { id: ToolID.MORTGAGE_CALCULATOR, title: 'Mortgage Calculator', description: 'Calculate monthly mortgage payments.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, isPopular: true, implemented: true },
  { id: ToolID.AUTO_LOAN_CALCULATOR, title: 'Auto Loan Calculator', description: 'Calculate car loan payments.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.EMI_CALCULATOR, title: 'EMI Calculator', description: 'Calculate monthly installments.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.SIP_CALCULATOR, title: 'SIP Calculator', description: 'Estimate investment returns.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, isPopular: true, implemented: true },
  { id: ToolID.GST_CALCULATOR, title: 'GST Calculator', description: 'Calculate tax amount.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, isPopular: true, implemented: true },
  { id: ToolID.INCOME_TAX_CALCULATOR, title: 'Income Tax Calc', description: 'Estimate annual tax.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.ROI_CALCULATOR, title: 'ROI Calculator', description: 'Calculate return on investment.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.CURRENCY_CONVERTER, title: 'Currency Converter', description: 'Convert currencies.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, isPopular: true, implemented: true },
  { id: ToolID.LUMPSUM_CALCULATOR, title: 'Lumpsum Calc', description: 'Calculate lumpsum returns.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.SWP_CALCULATOR, title: 'SWP Calculator', description: 'Systematic Withdrawal Plan.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.PPF_CALCULATOR, title: 'PPF Calculator', description: 'Public Provident Fund.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.FD_CALCULATOR, title: 'FD Calculator', description: 'Fixed Deposit returns.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.RD_CALCULATOR, title: 'RD Calculator', description: 'Recurring Deposit returns.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.STEP_UP_SIP_CALCULATOR, title: 'Step Up SIP', description: 'SIP with annual increase.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.CAGR_CALCULATOR, title: 'CAGR Calculator', description: 'Compound Annual Growth Rate.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.FUTURE_VALUE_CALCULATOR, title: 'Future Value', description: 'Calculate future value.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.SIMPLE_INTEREST_CALCULATOR, title: 'Simple Interest', description: 'Calculate simple interest.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.COMPOUND_INTEREST_CALCULATOR, title: 'Compound Interest', description: 'Calculate compound interest.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.INTEREST_RATE_CALCULATOR, title: 'Interest Rate', description: 'Find required rate.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.INTEREST_CALCULATOR, title: 'Interest Calc', description: 'Generic interest calc.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.SAVINGS_CALCULATOR, title: 'Savings Calc', description: 'Plan savings growth.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.CD_CALCULATOR, title: 'CD Calculator', description: 'Certificate of Deposit.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.BOND_CALCULATOR, title: 'Bond Calculator', description: 'Calculate bond yield/price.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.AVERAGE_RETURN_CALCULATOR, title: 'Avg Return', description: 'Calculate average returns.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.PAYBACK_PERIOD_CALCULATOR, title: 'Payback Period', description: 'Investment recovery time.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.PRESENT_VALUE_CALCULATOR, title: 'Present Value', description: 'Calculate PV.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.IRR_CALCULATOR, title: 'IRR Calculator', description: 'Internal Rate of Return.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.INVESTMENT_CALCULATOR, title: 'Investment Calc', description: 'Plan investments.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.INFLATION_CALCULATOR, title: 'Inflation Calc', description: 'Calculate future cost.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.DEPRECIATION_CALCULATOR, title: 'Depreciation', description: 'Asset value over time.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.COMMISSION_CALCULATOR, title: 'Commission', description: 'Calculate sales commission.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.MARGIN_CALCULATOR, title: 'Margin Calc', description: 'Profit margin & markup.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.GDP_CALCULATOR, title: 'GDP Calculator', description: 'Calculate Gross Domestic Product.', icon: Icons.BarChart, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.TIP_CALCULATOR, title: 'Tip Calculator', description: 'Calculate tips and split bills.', icon: Icons.Calculator, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.BILL_SPLITTER, title: 'Bill Splitter', description: 'Split bills and calculate tips easily.', icon: Icons.Calculator, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.VAT_CALCULATOR, title: 'VAT Calculator', description: 'Calculate Value Added Tax.', icon: Icons.Calculator, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.DEBT_TO_INCOME_RATIO_CALCULATOR, title: 'Debt-to-Income Ratio', description: 'Calculate your DTI ratio to assess financial health.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.DISCOUNT_CALCULATOR, title: 'Discount Calculator', description: 'Calculate final price after discount.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, isPopular: true, implemented: true },
  { id: ToolID.CREDIT_CARD_PAYOFF_CALCULATOR, title: 'Credit Card Payoff', description: 'Calculate months to pay off debt.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.RENT_VS_BUY_CALCULATOR, title: 'Rent vs. Buy', description: 'Compare renting vs. buying a home.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.STOCK_PROFIT_CALCULATOR, title: 'Stock Profit Calc', description: 'Calculate stock trading profits.', icon: Icons.BarChart, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.BREAK_EVEN_CALCULATOR, title: 'Break-Even Analysis', description: 'Calculate break-even point.', icon: Icons.BarChart, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.RETIREMENT_CORPUS_CALCULATOR, title: 'Retirement Calculator', description: 'Plan your retirement savings.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.HOURLY_TO_SALARY_CALCULATOR, title: 'Hourly to Salary', description: 'Convert hourly wage to annual salary.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.EMERGENCY_FUND_CALCULATOR, title: 'Emergency Fund', description: 'Calculate required emergency savings.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.CAP_RATE_CALCULATOR, title: 'Cap Rate Calculator', description: 'Calculate property capitalization rate.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.RULE_OF_72_CALCULATOR, title: 'Rule of 72', description: 'Estimate years to double investment.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.DIVIDEND_YIELD_CALCULATOR, title: 'Dividend Yield', description: 'Calculate stock dividend yield.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.NPV_CALCULATOR, title: 'NPV Calculator', description: 'Calculate Net Present Value.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.NET_WORTH_CALCULATOR, title: 'Net Worth Calculator', description: 'Calculate assets minus liabilities.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },
  { id: ToolID.FIRE_CALCULATOR, title: 'FIRE Calculator', description: 'Financial Independence, Retire Early.', icon: Icons.Calculator, category: ToolCategory.FINANCIAL, implemented: true },

  // --- Fitness Tools ---
  { id: ToolID.BMI_CALCULATOR, title: 'BMI Calculator', description: 'Body Mass Index.', icon: Icons.Calculator, category: ToolCategory.FITNESS, isPopular: true, implemented: true },
  { id: ToolID.BMR_CALCULATOR, title: 'BMR Calculator', description: 'Basal Metabolic Rate.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.BODY_FAT_CALCULATOR, title: 'Body Fat Calc', description: 'Estimate body fat %.', icon: Icons.Calculator, category: ToolCategory.FITNESS, isPopular: true, implemented: true },
  { id: ToolID.CALORIE_CALCULATOR, title: 'Calorie Calculator', description: 'Daily calorie needs.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.IDEAL_WEIGHT_CALCULATOR, title: 'Ideal Weight', description: 'Find healthy weight.', icon: Icons.Scale, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.WATER_INTAKE_CALCULATOR, title: 'Water Intake', description: 'Daily water needs.', icon: Icons.Beaker, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.PACE_CALCULATOR, title: 'Pace Calculator', description: 'Calculate running pace.', icon: Icons.Clock, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.ARMY_BODY_FAT_CALCULATOR, title: 'Army Body Fat', description: 'US Army standard.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.LEAN_BODY_MASS_CALCULATOR, title: 'Lean Mass Calc', description: 'Calculate lean mass.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.HEALTHY_WEIGHT_CALCULATOR, title: 'Healthy Weight', description: 'Healthy weight range.', icon: Icons.Scale, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.CALORIES_BURNED_CALCULATOR, title: 'Calories Burned', description: 'Calories from exercise.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.ONE_REP_MAX_CALCULATOR, title: 'One Rep Max', description: 'Max weight limit.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.TARGET_HEART_RATE_CALCULATOR, title: 'Target Heart Rate', description: 'Exercise heart zones.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.MACRO_CALCULATOR, title: 'Macro Calculator', description: 'Protein, Carbs, Fat.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.CARBOHYDRATE_CALCULATOR, title: 'Carb Calculator', description: 'Daily carb intake.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.PROTEIN_CALCULATOR, title: 'Protein Calculator', description: 'Daily protein intake.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.FAT_INTAKE_CALCULATOR, title: 'Fat Intake Calc', description: 'Daily fat intake.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.TDEE_CALCULATOR, title: 'TDEE Calculator', description: 'Total Energy Expenditure.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.GFR_CALCULATOR, title: 'GFR Calculator', description: 'Kidney function.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.BODY_TYPE_CALCULATOR, title: 'Body Type Calc', description: 'Determine body shape.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.BODY_SURFACE_AREA_CALCULATOR, title: 'Body Surface Area', description: 'Calculate BSA.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.BAC_CALCULATOR, title: 'BAC Calculator', description: 'Blood Alcohol Content.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.PREGNANCY_CALCULATOR, title: 'Pregnancy Calc', description: 'Estimated due date.', icon: Icons.Calculator, category: ToolCategory.FITNESS, isPopular: true, implemented: true },
  { id: ToolID.PREGNANCY_WEIGHT_GAIN_CALCULATOR, title: 'Pregnancy Weight', description: 'Healthy weight gain.', icon: Icons.Scale, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.PREGNANCY_CONCEPTION_CALCULATOR, title: 'Conception Date', description: 'Estimate conception.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.DUE_DATE_CALCULATOR, title: 'Due Date Calc', description: 'Baby due date.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.OVULATION_CALCULATOR, title: 'Ovulation Calc', description: 'Fertile window.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.CONCEPTION_CALCULATOR, title: 'Conception Calc', description: 'When did it happen?', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.PERIOD_CALCULATOR, title: 'Period Calculator', description: 'Next cycle date.', icon: Icons.Calculator, category: ToolCategory.FITNESS, implemented: true },
  { id: ToolID.STEP_COUNTER_TO_DISTANCE, title: 'Steps to Distance', description: 'Convert steps to km/miles.', icon: Icons.Walk, category: ToolCategory.OTHER, implemented: true },

  // Date & Time Tools
  { id: ToolID.AGE_CALCULATOR, title: 'Age Calculator', description: 'Calculate precise age.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, isPopular: true, implemented: true },
  { id: ToolID.DATE_DIFFERENCE, title: 'Date Difference', description: 'Duration between dates.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, isPopular: true, implemented: true },
  { id: ToolID.TIME_ADD_SUBTRACT, title: 'Add/Sub Time', description: 'Add time to date.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.DATE_CALCULATOR, title: 'Date Calculator', description: 'Add days to date.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.TIME_CALCULATOR, title: 'Time Calculator', description: 'Add hours/minutes.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.HOURS_CALCULATOR, title: 'Hours Calc', description: 'Hours between times.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.TIME_CARD_CALCULATOR, title: 'Time Card', description: 'Weekly work hours.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.TIME_ZONE_CALCULATOR, title: 'Time Zone', description: 'Convert time zones.', icon: Icons.Globe, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.TIME_DURATION_CALCULATOR, title: 'Duration Calc', description: 'Time span calc.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.DAY_COUNTER, title: 'Day Counter', description: 'Count days.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.DAY_OF_WEEK_CALCULATOR, title: 'Day of Week', description: 'Find weekday.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, implemented: true },
  // New Date & Time Tools
  { id: ToolID.STOPWATCH, title: 'Stopwatch', description: 'Online stopwatch with lap splits.', icon: Icons.Stopwatch, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.COUNTDOWN_TIMER, title: 'Countdown Timer', description: 'Custom timer with alarm.', icon: Icons.Timer, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.BUSINESS_DAYS_CALCULATOR, title: 'Business Days Calc', description: 'Count weekdays between dates.', icon: Icons.Work, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.POMODORO_TIMER, title: 'Pomodoro Timer', description: 'Focus and break interval timer.', icon: Icons.Timer, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.TIME_TO_DECIMAL_CONVERTER, title: 'Time to Decimal', description: 'Convert HH:MM to decimal hours.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.CALENDAR_GENERATOR, title: 'Calendar Generator', description: 'Printable monthly/yearly calendar.', icon: Icons.Date, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.WEEK_NUMBER_CALCULATOR, title: 'Week Number Calc', description: 'Find ISO week number.', icon: Icons.Calculator, category: ToolCategory.DATE_TIME, implemented: true },
  { id: ToolID.LEAP_YEAR_CHECKER, title: 'Leap Year Checker', description: 'Check if year is a leap year.', icon: Icons.Check, category: ToolCategory.DATE_TIME, implemented: true },

  // Other Tools
  { id: ToolID.RANDOM_NUMBER_GENERATOR, title: 'Random Number Gen', description: 'Generate random numbers within a range.', icon: Icons.Numbers, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.EPOCH_CONVERTER, title: 'Epoch Converter', description: 'Convert Unix timestamps to human-readable dates.', icon: Icons.Clock, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.CREATE_ZIP, title: 'Create Zip', description: 'Create and download zip files from multiple files.', icon: Icons.Compress, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.YES_NO_GENERATOR, title: 'Yes/No Generator', description: 'Get a quick Yes, No, or Maybe decision.', icon: Icons.Check, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.COIN_FLIP, title: 'Coin Flip', description: 'Flip up to 3 coins simultaneously.', icon: Icons.Circle, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.DICE_ROLLER, title: 'Dice Roller', description: 'Roll one or two 6-sided dice.', icon: Icons.Cube, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.ROMAN_NUMERAL_CONVERTER, title: 'Roman Numeral', description: 'Convert numbers to Roman numerals.', icon: Icons.Calculator, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.CHINESE_ZODIAC_CALCULATOR, title: 'Chinese Zodiac', description: 'Find your Chinese Zodiac sign.', icon: Icons.Dragon, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.PRIME_NUMBER_GENERATOR, title: 'Prime Number Generator', description: 'Find prime numbers within a range.', icon: Icons.Numbers, category: ToolCategory.OTHER, implemented: true },
  { id: ToolID.LEET_SPEAK_TRANSLATOR, title: 'Leet Speak Translator', description: 'Convert text to 1337 sp34k.', icon: Icons.Code, category: ToolCategory.TEXT, implemented: true },
];
