
import React from 'react';

export type PageType = 'privacy' | 'terms' | 'cookies' | 'about' | 'contact' | 'blog' | null;

export enum ToolCategory {
  ALL = 'All Tools',
  PDF = 'PDF & File',
  IMAGE = 'Image Tools',
  TEXT = 'Text & Encoding', // New Category
  SEO = 'SEO Tools',
  FINANCIAL = 'Financial',
  DATE_TIME = 'Date & Time',
  FITNESS = 'Fitness & Health',
  MATH_SCIENCE = 'Math & Science',
  UNIT_CONVERTER = 'Unit Converter',
  OTHER = 'Other Tools',
}

export enum ToolID {
  // PDF Editor
  PDF_EDITOR = 'pdf-editor',
  ESIGN_PDF = 'esign-pdf',

  // Unit Converters
  LENGTH_CONVERTER = 'length-converter',
  WEIGHT_CONVERTER = 'weight-converter',
  TEMPERATURE_CONVERTER = 'temperature-converter',
  AREA_CONVERTER = 'area-converter',
  VOLUME_CONVERTER = 'volume-converter',
  SPEED_CONVERTER = 'speed-converter',
  DATA_CONVERTER = 'data-converter',
  TIME_CONVERTER = 'time-converter',
  FUEL_CONVERTER = 'fuel-converter',
  PRESSURE_CONVERTER = 'pressure-converter',
  FREQUENCY_CONVERTER = 'frequency-converter',
  ANGLE_CONVERTER = 'angle-converter',
  SHOES_SIZE_CONVERTER = 'shoes-size-converter',
  ROMAN_NUMERAL_CONVERTER = 'roman-numeral-converter',
  // New Unit Converters
  POWER_CONVERTER = 'power-converter',
  ENERGY_CONVERTER = 'energy-converter',
  NUMBER_BASE_CONVERTER = 'number-base-converter',
  BITRATE_CONVERTER = 'bitrate-converter',
  TORQUE_CONVERTER = 'torque-converter',
  FORCE_CONVERTER = 'force-converter',
  DENSITY_CONVERTER = 'density-converter',
  ILLUMINANCE_CONVERTER = 'illuminance-converter',

  // Math & Science Tools
  TRIANGLE_CALCULATOR = 'triangle-calculator',
  VOLUME_CALCULATOR = 'volume-calculator',
  SLOPE_CALCULATOR = 'slope-calculator',
  AREA_CALCULATOR = 'area-calculator',
  DISTANCE_CALCULATOR = 'distance-calculator',
  CIRCLE_CALCULATOR = 'circle-calculator',
  SURFACE_AREA_CALCULATOR = 'surface-area-calculator',
  PYTHAGOREAN_CALCULATOR = 'pythagorean-calculator',
  RIGHT_TRIANGLE_CALCULATOR = 'right-triangle-calculator',
  LCM_GCD_CALCULATOR = 'lcm-gcd-calculator',
  PERCENTAGE_TO_CGPA = 'percentage-to-cgpa',
  BINARY_CALCULATOR = 'binary-calculator',
  // New Math & Science Tools
  PERCENTAGE_CALCULATOR = 'percentage-calculator',
  STATISTICS_CALCULATOR = 'statistics-calculator',
  QUADRATIC_SOLVER = 'quadratic-solver',
  FRACTION_CALCULATOR = 'fraction-calculator',
  PERMUTATION_COMBINATION_CALCULATOR = 'permutation-combination-calculator',
  PRIME_FACTORIZATION_TOOL = 'prime-factorization-tool',
  FORCE_CALCULATOR = 'force-calculator',
  OHMS_LAW_CALCULATOR = 'ohms-law-calculator',

  // SEO Tools
  META_TAG_GENERATOR = 'meta-tag-generator',
  KEYWORD_DENSITY_CHECKER = 'keyword-density-checker',
  READABILITY_SCORE = 'readability-score',
  CHARACTER_COUNTER = 'character-counter',
  WORD_COUNTER = 'word-counter',
  HEADING_TAG_ANALYZER = 'heading-tag-analyzer',
  ALT_TEXT_GENERATOR = 'alt-text-generator',
  ROBOTS_TXT_GENERATOR = 'robots-txt-generator',
  SITEMAP_GENERATOR = 'sitemap-generator',
  OPEN_GRAPH_GENERATOR = 'open-graph-generator',
  SCHEMA_MARKUP_GENERATOR = 'schema-markup-generator',
  CANONICAL_TAG_GENERATOR = 'canonical-tag-generator',
  // New SEO Tools
  GOOGLE_SERP_SIMULATOR = 'google-serp-simulator',
  UTM_LINK_GENERATOR = 'utm-link-generator',
  KEYWORD_PERMUTATION_GENERATOR = 'keyword-permutation-generator',
  HTACCESS_REDIRECT_GENERATOR = 'htaccess-redirect-generator',
  HTML_TEXT_RATIO_CALCULATOR = 'html-text-ratio-calculator',
  PPC_KEYWORD_WRAPPER = 'ppc-keyword-wrapper',
  BULK_URL_OPENER = 'bulk-url-opener',
  LINK_EXTRACTOR = 'link-extractor',

  // Image Tools (Client Side)
  COMPRESS_IMAGE = 'compress-image',
  RESIZE_IMAGE = 'resize-image',
  CROP_IMAGE = 'crop-image',
  ROTATE_IMAGE = 'rotate-image',
  ROUND_IMAGE = 'round-image',
  FLIP_IMAGE = 'flip-image',
  TO_GRAYSCALE = 'to-grayscale',
  BLACK_AND_WHITE = 'black-and-white',
  IMAGE_TO_SKETCH = 'image-to-sketch',
  IMAGE_TO_BASE64 = 'image-to-base64',
  BASE64_TO_IMAGE = 'base64-to-image',
  
  // Image Converters
  HEIC_TO_JPG = 'heic-to-jpg',
  WEBP_TO_JPG = 'webp-to-jpg',
  PNG_TO_JPG = 'png-to-jpg',
  WEBP_TO_PNG = 'webp-to-png',
  JPG_TO_PNG = 'jpg-to-png',
  PNG_TO_WEBP = 'png-to-webp',
  JPG_TO_WEBP = 'jpg-to-webp',
  PNG_TO_SVG = 'png-to-svg',
  JPG_TO_SVG = 'jpg-to-svg',
  HEIC_TO_PNG = 'heic-to-png',
  SVG_TO_PNG = 'svg-to-png',
  GIF_TO_MP4 = 'gif-to-mp4',
  JPG_TO_GIF = 'jpg-to-gif',
  TIFF_TO_JPG = 'tiff-to-jpg',
  WEBP_TO_GIF = 'webp-to-gif',
  PNG_TO_EPS = 'png-to-eps',
  PNG_TO_GIF = 'png-to-gif',
  JPG_TO_TIFF = 'jpg-to-tiff',
  EPS_TO_PNG = 'eps-to-png',
  TIFF_TO_PNG = 'tiff-to-png',
  GIF_TO_PNG = 'gif-to-png',
  PNG_TO_TIFF = 'png-to-tiff',
  EPS_TO_JPG = 'eps-to-jpg',
  EPS_TO_SVG = 'eps-to-svg',
  JPG_TO_AVIF = 'jpg-to-avif',
  GIF_TO_AVIF = 'gif-to-avif',
  VSD_TO_PDF = 'vsd-to-pdf',
  PNG_TO_AVIF = 'png-to-avif',
  PSD_TO_SVG = 'psd-to-svg',
  TIFF_TO_SVG = 'tiff-to-svg',
  VSDX_TO_PDF = 'vsdx-to-pdf',
  VSDX_TO_PPTX = 'vsdx-to-pptx',
  VSDX_TO_DOCX = 'vsdx-to-docx',
  WEBP_TO_AVIF = 'webp-to-avif',
  VSDX_TO_JPG = 'vsdx-to-jpg',
  VSD_TO_DOCX = 'vsd-to-docx',
  HEIC_TO_AVIF = 'heic-to-avif',
  VSD_TO_JPG = 'vsd-to-jpg',
  PNG_TO_HEIC = 'png-to-heic',
  PNG_TO_VSD = 'png-to-vsd',
  PNG_TO_VSDX = 'png-to-vsdx',

  // PDF Tools
  PDF_MERGE = 'pdf-merge', 
  PDF_TO_JPG = 'pdf-to-jpg',
  JPG_TO_PDF = 'jpg-to-pdf',
  COMPRESS_PDF = 'compress-pdf',
  SPLIT_PDF = 'split-pdf',
  PDF_TO_WORD = 'pdf-to-word',
  WORD_TO_PDF = 'word-to-pdf',
  UNLOCK_PDF = 'unlock-pdf',
  LOCK_PDF = 'lock-pdf',
  CROP_PDF = 'crop-pdf',
  PDF_TO_EXCEL = 'pdf-to-excel',
  PDF_TO_POWERPOINT = 'pdf-to-powerpoint',
  PNG_TO_PDF = 'png-to-pdf',
  EPUB_TO_PDF = 'epub-to-pdf',
  ROTATE_PDF = 'rotate-pdf',
  ADD_PAGE_NUMBERS = 'add-page-numbers',
  ADD_WATERMARK = 'add-watermark',
  PDF_TO_PNG = 'pdf-to-png',
  PDF_TO_HTML = 'pdf-to-html',
  PDF_TO_TEXT = 'pdf-to-text',
  PDF_TO_EPUB = 'pdf-to-epub',
  EXCEL_TO_PDF = 'excel-to-pdf',
  POWERPOINT_TO_PDF = 'powerpoint-to-pdf',
  IMAGE_TO_PDF = 'image-to-pdf',
  DELETE_PDF_PAGES = 'delete-pdf-pages',
  REARRANGE_PDF = 'rearrange-pdf',
  GIF_TO_PDF = 'gif-to-pdf',
  REPAIR_PDF = 'repair-pdf', 

  // Data Converters
  CSV_TO_EXCEL = 'csv-to-excel',
  XML_TO_EXCEL = 'xml-to-excel',
  JSON_TO_XML = 'json-to-xml',
  EXCEL_TO_CSV = 'excel-to-csv',
  XML_TO_CSV = 'xml-to-csv',
  CSV_TO_JSON = 'csv-to-json',
  XML_TO_JSON = 'xml-to-json',
  EXCEL_TO_XML = 'excel-to-xml',
  CSV_TO_XML = 'csv-to-xml',

  // Financial Tools
  LOAN_CALCULATOR = 'loan-calculator',
  ROI_CALCULATOR = 'roi-calculator',
  SIP_CALCULATOR = 'sip-calculator',
  LUMPSUM_CALCULATOR = 'lumpsum-calculator',
  SWP_CALCULATOR = 'swp-calculator',
  PPF_CALCULATOR = 'ppf-calculator',
  FD_CALCULATOR = 'fd-calculator',
  RD_CALCULATOR = 'rd-calculator',
  STEP_UP_SIP_CALCULATOR = 'step-up-sip-calculator',
  CAGR_CALCULATOR = 'cagr-calculator',
  FUTURE_VALUE_CALCULATOR = 'future-value-calculator',
  EMI_CALCULATOR = 'emi-calculator',
  INCOME_TAX_CALCULATOR = 'income-tax-calculator',
  GST_CALCULATOR = 'gst-calculator',
  SIMPLE_INTEREST_CALCULATOR = 'simple-interest-calculator',
  COMPOUND_INTEREST_CALCULATOR = 'compound-interest-calculator',
  INTEREST_RATE_CALCULATOR = 'interest-rate-calculator',
  INTEREST_CALCULATOR = 'interest-calculator',
  SAVINGS_CALCULATOR = 'savings-calculator',
  CD_CALCULATOR = 'cd-calculator',
  BOND_CALCULATOR = 'bond-calculator',
  AVERAGE_RETURN_CALCULATOR = 'average-return-calculator',
  PAYBACK_PERIOD_CALCULATOR = 'payback-period-calculator',
  PRESENT_VALUE_CALCULATOR = 'present-value-calculator',
  IRR_CALCULATOR = 'irr-calculator',
  INVESTMENT_CALCULATOR = 'investment-calculator',
  CURRENCY_CONVERTER = 'currency-converter',
  INFLATION_CALCULATOR = 'inflation-calculator',
  DEPRECIATION_CALCULATOR = 'depreciation-calculator',
  COMMISSION_CALCULATOR = 'commission-calculator',
  MARGIN_CALCULATOR = 'margin-calculator',
  GDP_CALCULATOR = 'gdp-calculator',
  TIP_CALCULATOR = 'tip-calculator',
  BILL_SPLITTER = 'bill-splitter',
  VAT_CALCULATOR = 'vat-calculator',
  DEBT_TO_INCOME_RATIO_CALCULATOR = 'debt-to-income-ratio-calculator',
  MORTGAGE_CALCULATOR = 'mortgage-calculator',
  DISCOUNT_CALCULATOR = 'discount-calculator',
  CREDIT_CARD_PAYOFF_CALCULATOR = 'credit-card-payoff-calculator',
  RENT_VS_BUY_CALCULATOR = 'rent-vs-buy-calculator',
  STOCK_PROFIT_CALCULATOR = 'stock-profit-calculator',
  BREAK_EVEN_CALCULATOR = 'break-even-calculator',
  AUTO_LOAN_CALCULATOR = 'auto-loan-calculator',
  RETIREMENT_CORPUS_CALCULATOR = 'retirement-corpus-calculator',
  HOURLY_TO_SALARY_CALCULATOR = 'hourly-to-salary-calculator',
  EMERGENCY_FUND_CALCULATOR = 'emergency-fund-calculator',
  CAP_RATE_CALCULATOR = 'cap-rate-calculator',
  RULE_OF_72_CALCULATOR = 'rule-of-72-calculator',
  DIVIDEND_YIELD_CALCULATOR = 'dividend-yield-calculator',
  NPV_CALCULATOR = 'npv-calculator',
  NET_WORTH_CALCULATOR = 'net-worth-calculator',
  FIRE_CALCULATOR = 'fire-calculator',

  // Fitness Tools
  BMI_CALCULATOR = 'bmi-calculator',
  BMR_CALCULATOR = 'bmr-calculator',
  BODY_FAT_CALCULATOR = 'body-fat-calculator',
  CALORIE_CALCULATOR = 'calorie-calculator',
  IDEAL_WEIGHT_CALCULATOR = 'ideal-weight-calculator',
  WATER_INTAKE_CALCULATOR = 'water-intake-calculator',
  PACE_CALCULATOR = 'pace-calculator',
  ARMY_BODY_FAT_CALCULATOR = 'army-body-fat-calculator',
  LEAN_BODY_MASS_CALCULATOR = 'lean-body-mass-calculator',
  HEALTHY_WEIGHT_CALCULATOR = 'healthy-weight-calculator',
  CALORIES_BURNED_CALCULATOR = 'calories-burned-calculator',
  ONE_REP_MAX_CALCULATOR = 'one-rep-max-calculator',
  TARGET_HEART_RATE_CALCULATOR = 'target-heart-rate-calculator',
  MACRO_CALCULATOR = 'macro-calculator',
  CARBOHYDRATE_CALCULATOR = 'carbohydrate-calculator',
  PROTEIN_CALCULATOR = 'protein-calculator',
  FAT_INTAKE_CALCULATOR = 'fat-intake-calculator',
  TDEE_CALCULATOR = 'tdee-calculator',
  GFR_CALCULATOR = 'gfr-calculator',
  BODY_TYPE_CALCULATOR = 'body-type-calculator',
  BODY_SURFACE_AREA_CALCULATOR = 'body-surface-area-calculator',
  BAC_CALCULATOR = 'bac-calculator',
  PREGNANCY_CALCULATOR = 'pregnancy-calculator',
  PREGNANCY_WEIGHT_GAIN_CALCULATOR = 'pregnancy-weight-gain-calculator',
  PREGNANCY_CONCEPTION_CALCULATOR = 'pregnancy-conception-calculator',
  DUE_DATE_CALCULATOR = 'due-date-calculator',
  OVULATION_CALCULATOR = 'ovulation-calculator',
  CONCEPTION_CALCULATOR = 'conception-calculator',
  PERIOD_CALCULATOR = 'period-calculator',
  STEP_COUNTER_TO_DISTANCE = 'step-counter-to-distance',

  // Date & Time Tools
  AGE_CALCULATOR = 'age-calculator',
  DATE_DIFFERENCE = 'date-difference',
  TIME_ADD_SUBTRACT = 'time-add-subtract',
  DATE_CALCULATOR = 'date-calculator',
  TIME_CALCULATOR = 'time-calculator',
  HOURS_CALCULATOR = 'hours-calculator',
  TIME_CARD_CALCULATOR = 'time-card-calculator',
  TIME_ZONE_CALCULATOR = 'time-zone-calculator',
  TIME_DURATION_CALCULATOR = 'time-duration-calculator',
  DAY_COUNTER = 'day-counter',
  DAY_OF_WEEK_CALCULATOR = 'day-of-week-calculator',
  // New Date & Time Tools
  STOPWATCH = 'stopwatch',
  COUNTDOWN_TIMER = 'countdown-timer',
  BUSINESS_DAYS_CALCULATOR = 'business-days-calculator',
  POMODORO_TIMER = 'pomodoro-timer',
  TIME_TO_DECIMAL_CONVERTER = 'time-to-decimal-converter',
  CALENDAR_GENERATOR = 'calendar-generator',
  WEEK_NUMBER_CALCULATOR = 'week-number-calculator',
  LEAP_YEAR_CHECKER = 'leap-year-checker',

  // Other Tools
  LOREM_IPSUM_GENERATOR = 'lorem-ipsum-generator',
  RANDOM_NUMBER_GENERATOR = 'random-number-generator',
  EPOCH_CONVERTER = 'epoch-converter',
  CREATE_ZIP = 'create-zip',
  YES_NO_GENERATOR = 'yes-no-generator',
  COIN_FLIP = 'coin-flip',
  DICE_ROLLER = 'dice-roller',
  TEXT_TO_BINARY = 'text-to-binary',
  BINARY_TO_TEXT = 'binary-to-text',
  CHINESE_ZODIAC_CALCULATOR = 'chinese-zodiac-calculator',
  MORSE_CODE_TRANSLATOR = 'morse-code-translator',
  MORSE_CODE_GENERATOR = 'morse-code-generator',
  PRIME_NUMBER_GENERATOR = 'prime-number-generator',
  LEET_SPEAK_TRANSLATOR = 'leet-speak-translator',
  BASE64_ENCODER_DECODER = 'base64-encoder-decoder',
  URL_ENCODER_DECODER = 'url-encoder-decoder',
  CASE_CONVERTER = 'case-converter',
  JSON_FORMATTER = 'json-formatter',
  REMOVE_DUPLICATE_LINES = 'remove-duplicate-lines',
  TEXT_REVERSER = 'text-reverser',
  SLUG_GENERATOR = 'slug-generator',
  HASH_GENERATOR = 'hash-generator',
  
  // Text Tools
  TEXT_DIFF_CHECKER = 'text-diff-checker',
  UUID_GENERATOR = 'uuid-generator',
  HTML_ENTITY_ENCODER = 'html-entity-encoder',
  LIST_SORTER = 'list-sorter',
  PASSWORD_GENERATOR = 'password-generator',
  STRIP_HTML = 'strip-html',
  ADD_LINE_NUMBERS = 'add-line-numbers',
  COLOR_CONVERTER = 'color-converter',
  // New Text Tools
  URL_DECODER = 'url-decoder',
  URL_ENCODER = 'url-encoder',
  SHA1_GENERATOR = 'sha1-generator',
  SHA256_GENERATOR = 'sha256-generator',
  SHA384_GENERATOR = 'sha384-generator',
  SHA512_GENERATOR = 'sha512-generator',
  TEXT_STATISTICS = 'text-statistics',
  URL_SANITIZER = 'url-sanitizer',
}

export interface ToolDefinition {
  id: ToolID;
  title: string;
  description: string;
  icon: React.ReactNode;
  category: ToolCategory;
  isPopular?: boolean;
  implemented: boolean;
}
